[[nodes]]
name = "instancia1"
host = "10.128.0.1"
user = "ubuntu"
private_key_path = "/home/user/.ssh/id_rsa"

[[nodes]]
name = "instancia2"
host = "10.128.0.2"
user = "ubuntu"
private_key_path = "/home/user/.ssh/id_rsa"
